export * from './capitalize/capitalize.function';
export * from './generate-week/generate-week.function';
export * from './generate-month/generate-month.function';
export * from './get-window-size/get-window-size.function';
export * from './get-window-width/get-window-width.function';
export * from './get-window-height/get-window-height.function';
export * from './generate-dates-array/generate-dates-array.function';
export * from './get-month-name-by-id/get-month-name-by-id.function';
export * from './get-last-name-initials/get-last-name-initials.function';
